/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.gradleup.shadow") version "9.0.0-rc2"
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.19"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.mikeprimm.com/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    paperweight.paperDevBundle("1.21.8-R0.1-SNAPSHOT")
    api("io.papermc:paperlib:1.0.8-SNAPSHOT")
    //compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly("us.dynmap:DynmapCoreAPI:3.7-beta-6")
    compileOnly("us.dynmap:dynmap-api:3.7-beta-6")
}

group = "com.wimbli.WorldBorder"
version = "2.1.5"
description = "WorldBorder"
java.sourceCompatibility = JavaVersion.VERSION_23

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    archiveBaseName.set("WorldBorder")
    archiveClassifier.set("")
    archiveVersion.set("")
}